services:
  # FastAPI Backend
  - type: web
    name: bsdsteel-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        value: postgresql+asyncpg://postgres.jjkilhyzebxjzwzppxbv:%23Bsdsteel%407.@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
      - key: JWT_SECRET_KEY
        value: 8e5f4620634bec876feec393e194e984c7619a9df2f6c06d28c87cb162860945
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 480
      - key: FRONTEND_URL
        value: https://bsdpoc-hcmn.vercel.app
